лабораторная_3
5ea6uck7horn/Repository_for_labs pull request #3
Opened 2024-11-03 17:46 UTC by 5ea6uck7horn

1 задание: всё ок
2 задание: встроенная в образовательный модуль проверка выдаёт ошибку. я не могу даже посмотреть правильный ответ, но проблем с содержанием и оформлением ответа я не вижу.
3 задание: всё ок, но модулю не нравится, что у меня 0.00 вместо 0.0 в ответе.

2024-11-06 03:45 UTC, 5ea6uck7horn commented
Возникла проблема: я выполнила и загрузила 3 лабораторную на гитхаб в это воскресенье, но, оказывается, у меня на СДО по какой-то причине ответ на задание висел в черновиках(( подскажите, пожалуйста, это всё равно считается за опоздание, или можно как-то кому-то доказать, что я сделала всё вовремя?

2024-11-06 17:10 UTC, rmushkin commented
> 1 задание: всё ок. 2 задание: встроенная в образовательный модуль проверка выдаёт ошибку. я не могу даже посмотреть правильный ответ, но проблем с содержанием и оформлением ответа я не вижу. 3 задание: всё ок, но модулю не нравится, что у меня 0.00 вместо 0.0 в ответе.

Это проще всего через f-стринги. Попробуйте докопаться до этого в [справке](https://docs.python.org/3/library/string.html#format-specification-mini-language), не получится - пишите, подскажу)



> Возникла проблема: я выполнила и загрузила 3 лабораторную на гитхаб в это воскресенье, но, оказывается, у меня на СДО по какой-то причине ответ на задание висел в черновиках(( подскажите, пожалуйста, это в любом случае считается за опоздание, или можно как-то кому-то доказать, что я сделала всё вовремя?

Не нужно ничего доказывать, тут есть таймстампы: 
![изображение](https://github.com/user-attachments/assets/510e8303-7c7c-4a87-85ab-4ae624985bca)
Ну и срок по 3 лабораторной до пятницы, так что тем более))

2024-11-07 19:18 UTC, rmushkin requested changes
Есть ряд замечаний, пожалуйста, порпавьте.

2024-11-07 19:18 UTC, rmushkin commented on лабораторная_3/lab3_2.py
> +    print(f'{intersection_set[0]}, {intersection_set[1]}')
Функция ничего не возвращает, только печатает на экран.

2024-11-07 19:18 UTC, rmushkin commented on лабораторная_3/lab3_2.py
> +    print(f'{intersection_set[0]}, {intersection_set[1]}')
Кроме того, почему только `[0]` и `[1]`? А если пересечение толще?

2024-11-07 19:18 UTC, rmushkin commented on лабораторная_3/lab3_3.py
> +    symb_dict = dict()
`symb` - плохое имя. Во-первых, это ненужное сокращение, во-вторых - это неверное использование английского слова (сторки состоят из character'ов)

2024-11-07 19:18 UTC, rmushkin commented on лабораторная_3/lab3_3.py
> +        del symb_dict[i]
`\r` забыли :)
А вообще, в python есть `.isalpha()`

2024-11-07 19:18 UTC, rmushkin commented on лабораторная_3/lab3_3.py
> +    symb_dict = dict()
(не ошибка) Нагляднее использовать конструктор пустого словаря `{}`

2024-11-07 19:18 UTC, rmushkin commented on лабораторная_3/lab3_3.py
> +        freq[letter] = round(value / summed_letters, 2)
Преждевременное округление. Физический смысл (ещё говорят "бизнес-логика") ничего не говорит об округлении частоты (в отличие, например, от денег из прошлой лабораторной). Поэтому тут округлние - исключительно фишка вывода на экран.

2024-11-07 19:18 UTC, rmushkin commented on лабораторная_3/lab3_3.py
> +    print(f'{letter}: {value}')
Вот тут округлению самое место.

2024-11-08 16:47 UTC, 5ea6uck7horn commented
> Ну и срок по 3 лабораторной до пятницы, так что тем более))

Ну вот это жёсткий дэдлайн, мягкий был как раз в воскресенье, а если сдать лабораторные после мягкого, их оценивают ниже...

2024-11-08 17:45 UTC, rmushkin commented
С 

> > Ну и срок по 3 лабораторной до пятницы, так что тем более))
> 
> Ну вот это жёсткий дэдлайн, мягкий был как раз в воскресенье, а если сдать лабораторные после мягкого, их оценивают ниже...

Нет. Они оцениваются точно так же :)

2024-11-08 17:49 UTC, rmushkin approved these changes
Принимается ✅

2024-11-08 17:49 UTC, merged